nnabla_context:
  context: cudnn
  device_id: 0
  type_config: float

data:
  lr_sdr_test: ./data/test/testset_SDR_x4.mat
  hr_hdr_test: ./data/test/testset_HDR.mat
  lr_sdr_train: ./data/train/SDR_youtube_80_x4.mat
  hr_hdr_train: ./data/train/HDR_youtube_80.mat
  val_data_size: 500
  d_name_test: SDR_YUV
  l_name_test: HDR_YUV
  d_name_train: SDR_data
  l_name_train: HDR_data

test_patch: 6
scaling_factor: 4
batch_size: 8
learning_rate: 0.0001
adv_weight_point: 250
lr_decreasing_factor: 0.1
test_img_dir: ./test_images
output_dir: ./model
pre_trained_model: None
detail_lambda: 0.5
jsigan: True
save_images: True
rec_lambda: 1.0
adv_lambda: 1
fm_lambda: 0.5
epoch: 260
gan_lr_linear_decay_point: 255
weight_decay: 0.0001
gan_ratio: 0.01
monitor_interval: 100
