defaults:
  - /proto_configs/train@_here_
  - _self_


## batch size
# Assumes 8 GPU. 
# According to the paper, total batch size should be 2048.
# For faster training, we use 256 batch size in total.
batch_size: 16
accum: 2
n_iters: 540000

## dump
# progress: False
output_dir: ./logdir/laion400m_64_imagen
# save_interval: 10000
# show_interval: 10
# gen_interval: 20000
# dump_grad_norm: True

## checkpointing
# resume: False

## loss
lr: 1.25e-5 # 1e-4 for bs=2048
# loss_scaling: 1.0
# clip_grad: 1.0
lr_scheduler: cosine

## augmentation
cond_drop_rate: 0.1